
name: Deploy in Github Package


on:

  workflow_dispatch:


jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Build cardgame
        uses: sebastien-perpignane/cardgame/.github/workflows/mvn-compile-develop.yml@master

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}