
name: Package standalone jar with jpackage

on:

  workflow_dispatch:

jobs:

  jpackage:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build standalone jar
        run: mvn -Pstandalone clean package

      - name: Run jpackage script
        run: |
          chmod +x scripts/jpackage.sh
          scripts/jpackage.sh

      - name: Upload standalone-cardgame artifact
        uses: actions/upload-artifact@v3
        with:
          name: standalone-cardgame
          path: target/cardgame.tgz
