name: Java compile with Maven

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  build-card-game:

    name: Build card-game

    uses: sebastien-perpignane/my-workflows/.github/workflows/mvn-java-workflow.yml@main
    with:
      java-version: '21'
      distribution: 'temurin'
