name: Java compile with Maven

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:

  build-card-game:

    name: Build card-game

    uses: sebastien-perpignane/my-workflows/.github/workflows/mvn-java-workflow.yml@main
    with:
      java-version: '21'
      distribution: 'temurin'
      upload-artifact: true

  sonar-analysis:

    name: sonarcloud analysis
    runs-on: ubuntu-latest
    needs: "build-card-game"

    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java_project
          path: ${{ github.workspace }}

      - name: Set up JDK ${{ inputs.java-version }}
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: 'Build and analyze'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=sebastien-perpignane_cardgame \
            -Dmaven.test.skip=true \
            -Dsonar.coverage.jacoco.xmlReportPaths='${project.reporting.outputDirectory}/merged-jacoco/jacoco.xml'
