name: Java compile with Maven

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:

  build-card-game:

    name: Build card-game

    uses: sebastien-perpignane/my-workflows/.github/workflows/mvn-java-workflow.yml@main
    with:
      java-version: '21'
      distribution: 'temurin'

  sonar-analysis:

    name: sonarcloud analysis

    steps:
      - name: 'Build and analyze'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sebastien-perpignane_cardgame
