name: Java compile with Maven

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  build:

    uses: sebastien-perpignane/my-workflows/.github/workflows/mvn-java-workflow.yml@main
    with:
      java-version: '17'
      distribution: 'temurin'


#    steps:
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Force all maven dependencies download for caching
#        run: mvn -B dependency:go-offline
#
#      - name: Build with Maven
#        run: mvn -B compile --file pom.xml -Dmaven.test.skip=true
#
#      - name: Unit tests
#        run: mvn -B test --file pom.xml
#
#      - name: Integration test
#        run: mvn -B failsafe:integration-test --file pom.xml
#
#      - name: Package
#        run: mvn -B package --file pom.xml -DskipTests=true
