name: Java compile with Maven

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B compile --file pom.xml -DskipTests=true

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Integration test
        run: mvn -B failsafe:integration-test --file pom.xml

      - name: Package
        run: mvn -B package --file pom.xml -DskipTests=true

      - name: build tar container
        run: mvn -B -fail-never jib:buildTar --file pom.xml

      - name: Show structure of current dir
        run: |
          pwd
          ls -R

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cardgame-jars
          path: | 
            target/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get artifacts from build
        uses: actions/download-artifact@v3
        with:
          name: cardgame-jars

      - name: Display structure of downloaded files
        run: ls -R